### PR TITLE
Use the new actor provider interface

### LINKED ISSUE #498: BlameableListener memory leak with FrankenPHP and unauthenticated requests
**Describe the bug**
When using FrankenPHP in worker mode the `user` inside the BlameableListener leaks to the next request.
It happens when the user is unauthenticated or authenticated but not `IS_AUTHENTICATED_REMEMBERED`: 
https://github.com/stof/StofDoctrineExtensionsBundle/blob/bf00701bff3f2b7c4bf6d963101c9ea6968d694f/src/EventListener/BlameListener.php#L45

**To Reproduce**
1. Create a Symfony project with FrankenPHP running in worker mode.
2. Authenticate a user and execute any requests that triggers the `KernelEvents::REQUEST` so the BlameListener is called.
3. Do an unauthenticated API-call that triggers the BlameListener and sets the `createdBy`.
4. The unauthenticated API-call will result in a 500 error because the entity is detached that is being set as `createdBy`.
As you might see the BlameableListener still uses the previously authenticated user.

**Expected behavior**
- The `setUserValue` should be called with a `null` value on the `kernel.reset` event to prevent leaking.
https://github.com/doctrine-extensions/DoctrineExtensions/blob/910c4ba96cc43153006cc46ba686a35b5231df69/src/Blameable/BlameableListener.php#L32

**Additional context**
I will work on a PR today.

### PR DESCRIPTION
**Pull request by mbabker**
Follows https://github.com/doctrine-extensions/DoctrineExtensions/pull/2914 and the 3.19 release
Replaces #499
Fixes #498
Probably implicitly fixes some other issues as well

### CODE REVIEW

File: src/Tool/TokenStorageActorProvider.php [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+            return null;
+        }
+
+        $token = $this->tokenStorage->getToken();
+
+        if (null === $token || !$this->authorizationChecker->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
+            return null;
+        }
+
+        return $token;
```
Comment (SherinBloemendaal) [inline src/Tool/TokenStorageActorProvider.php:36]:
```suggestion
        return $token->getUser();
```

Shouldn't we return the user instead of the security token?

Comment (stof) [reply src/Tool/TokenStorageActorProvider.php:36]: we should, indeed

File: src/Resources/config/tool.xml [hunk 2]
```diff
@@ -0,0 +1,16 @@
+<?xml version="1.0" encoding="UTF-8" ?>
+
+<container xmlns="http://symfony.com/schema/dic/services"
+    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+    xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
+
+    <parameters>
+        <parameter key="stof_doctrine_extensions.tool.actor_provider.class">Stof\DoctrineExtensionsBundle\Tool\TokenStorageActorProvider</parameter>
```
Comment (stof) [inline src/Resources/config/tool.xml:8]: Please put the class directly on the service instead. Defining service classes through parameters was common in the early days of Symfony, but it is not considered a best practice anymore as it is generally a very bad extension point (and it bloats the list of parameters)

File: src/Resources/config/tool.xml [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+    </parameters>
+    <services>
+        <service id="stof_doctrine_extensions.tool.actor_provider" class="%stof_doctrine_extensions.tool.actor_provider.class%">
```
Comment (stof) [inline src/Resources/config/tool.xml:11]:
```suggestion
        <service id="stof_doctrine_extensions.tool.actor_provider" class="%stof_doctrine_extensions.tool.actor_provider.class%" public="false">
```

The service should be private. We don't need to make it available through `$container->get()` at runtime as the expected usage is only to inject it in other services.

File: src/Resources/config/loggable.xml [hunk 4]
```diff
@@ -16,13 +16,16 @@
             <call method="setAnnotationReader">
                 <argument type="service" id=".stof_doctrine_extensions.reader" on-invalid="ignore" />
             </call>
+            <call method="setActorProvider">
+                <argument type="service" id="stof_doctrine_extensions.tool.actor_provider" />
+            </call>
         </service>
 
+        <!-- deprecated in favor of the actor provider -->
         <service id="stof_doctrine_extensions.event_listener.logger" class="%stof_doctrine_extensions.event_listener.logger.class%">
```
Comment (stof) [inline src/Resources/config/loggable.xml:25]: Please add the `<deprecated>` tag to properly mark the listener service as deprecated, and so the `@deprecated` annotation on the listener class (and we can then remove the comment).

File: src/Tool/TokenStorageActorProvider.php (hunk 1 above)
Comment (mbabker) [reply src/Tool/TokenStorageActorProvider.php:36]: Functionally it shouldn't matter.  The extensions are looking for an object with either a `getUserIdentifier()`, `getUsername()`, or `__toString()` method and `TokenInterface::getUserIdentifier()` does exist.  The difference then boils down to whether the token and user objects have different identifiers.  (FWIW the blame listener is passing the user and the loggable listener is passing the token, so one of them is "wrong" in some way)

File: src/Resources/config/tool.xml (hunk 2 above)
Comment (mbabker) [reply src/Resources/config/tool.xml]: Updated (most of this was just copy paste from what else was there so I didn't want to get too opinionated about using best practices 😅)

File: src/Resources/config/tool.xml (hunk 3 above)
Comment (mbabker) [reply src/Resources/config/tool.xml]: Updated

File: src/Resources/config/loggable.xml (hunk 4 above)
Comment (mbabker) [reply src/Resources/config/loggable.xml:24]: Updated

File: src/Tool/TokenStorageActorProvider.php (hunk 1 above)
Comment (stof) [reply src/Tool/TokenStorageActorProvider.php:36]: it does not matter when storing the value in a text field using `getUserIdentifier`. But it matters when storing it in an association.

Comment (mbabker) [reply src/Tool/TokenStorageActorProvider.php]: D'oh, right, I forgot blameable supports relations 🤦   It's updated

File: src/Tool/TokenStorageActorProvider.php [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+
+use Gedmo\Tool\ActorProviderInterface;
+use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
+use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
+use Symfony\Component\Security\Core\User\UserInterface;
+
+/**
+ * Provides an actor for the extensions using the token storage.
+ */
+class TokenStorageActorProvider implements ActorProviderInterface
```
Comment (stof) [inline src/Tool/TokenStorageActorProvider.php:13]: Can you make the class final and tag it as `@internal` ? I don't see any reason why a project would need to extend that class (they can implement the interface if they want) and I would prefer not having to maintain BC only for an hypothetical use case.

Comment (mbabker) [reply src/Tool/TokenStorageActorProvider.php]: Done!

**Review by stof — APPROVED** [review]

**Comment by stof** [comment]
Thanks @mbabker

**Comment by SherinBloemendaal** [comment]
@stof, just wondering if there's any ETA on the next release? Thanks so far :)

**Comment by stof** [comment]
I still have 1 change I want to do to be compatible with the new way of doing things (regarding the way the locale is handled). My plan is to do it this weekend (hopefully) and then do a release.

File: src/Resources/config/loggable.xml [hunk 6]
```diff
@@ -16,13 +16,16 @@
             <call method="setAnnotationReader">
                 <argument type="service" id=".stof_doctrine_extensions.reader" on-invalid="ignore" />
             </call>
+            <call method="setActorProvider">
+                <argument type="service" id="stof_doctrine_extensions.tool.actor_provider" />
+            </call>
```
[the remark this answers is not in the document]
Comment (bt-nn) [reply src/Resources/config/loggable.xml:21]: One of our projects was affected by it. It took a while to debug, but fortunately, the change was made quickly by creating a new ActorProvider and set the User there.
